[project]
name = "demo7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.1.3",
    "langchain-deepseek>=1.0.1",
]
